DROP DATABASE IF EXISTS KAKAO_T;

CREATE TABLE IF NOT EXISTS KAKAO_T;

USE KAKAO_T;

CREATE TABLE IF NOT EXISTS FAMILY
(
    family_id INT PRIMARY KEY AUTO_INCREMENT,
    user_id   INT NOT NULL
);

-- USER => 1_000_000
CREATE TABLE IF NOT EXISTS USER
(
    USER_ID      INT PRIMARY KEY AUTO_INCREMENT,
    NAME         VARCHAR(20) NOT NULL,
    PHONE_NUMBER CHAR(12)    NOT NULL UNIQUE,
    BIRTH        CHAR(6)     NOT NULL,
    POINT        INT         NOT NULL DEFAULT 0,
    FAMILY_ID    INT,
    FOREIGN KEY (FAMILY_ID) REFERENCES FAMILY (FAMILY_ID) ON DELETE SET NULL
);

ALTER TABLE USER AUTO_INCREMENT = 1000000;

CREATE TABLE IF NOT EXISTS PAYMENT_METHOD
(
    PAYMENT_INFO      CHAR(16) PRIMARY KEY,
    USER_ID           INT      NOT NULL,
    EXPIRATION_PERIOD CHAR(4)  NOT NULL,
    CVC               CHAR(3)  NOT NULL,
    PASSWORD          CHAR(2)  NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TAXI_CALL
(
    CALL_ID      INT PRIMARY KEY AUTO_INCREMENT,
    START_LONG   DOUBLE NOT NULL,
    START_LAT    DOUBLE NOT NULL,
    END_LONG     DOUBLE NOT NULL,
    END_LAT      DOUBLE NOT NULL,
    IS_PREMIUM   BOOL NOT NULL DEFAULT FALSE,
    APX_PAYMENT  INT NOT NULL DEFAULT 0,
    CALL_TIME    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_ID      INT,
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID) ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS REGION
(
    REGION VARCHAR(20) PRIMARY KEY,
    DIST   POLYGON     NOT NULL
);

-- 기사 및 사용자 ID 시작 번호 정하기
-- ID => 1
CREATE TABLE IF NOT EXISTS DRIVER
(
    DRIVER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME      VARCHAR(20)  NOT NULL,
    SSN       CHAR(13)     NOT NULL UNIQUE,
    COMPANY   VARCHAR(100) NOT NULL DEFAULT '개인',
    REGION    VARCHAR(20),
    RATING    DOUBLE,
    IS_QUIT   BOOL         NOT NULL DEFAULT FALSE,
    FOREIGN KEY (REGION) REFERENCES REGION (REGION)
);


CREATE TABLE IF NOT EXISTS CAR
(
    DRIVER_ID INT PRIMARY KEY,
    PAY_TYPE  BOOL         NOT NULL DEFAULT FALSE,
    CAR_NUM   CHAR(9)      NOT NULL UNIQUE,
    CAR_TYPE  VARCHAR(100) NOT NULL,
    FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (DRIVER_ID)
);

CREATE TABLE IF NOT EXISTS TAXI_CATCH
(
    CATCH_ID   INT PRIMARY KEY AUTO_INCREMENT,
    CALL_ID    INT NOT NULL,
    DRIVER_ID  INT NOT NULL,
    RATING     DOUBLE,
    COMMENT    VARCHAR(100),
    CATCH_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CALL_ID) REFERENCES TAXI_CALL (CALL_ID),
    FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (DRIVER_ID)
);

CREATE TABLE IF NOT EXISTS PAYMENT
(
    CATCH_ID       INT PRIMARY KEY,
    PAYMENT_RESULT INT DEFAULT 0,
    CARD_NUM       CHAR(16) NOT NULL,
    PAYMENT_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CATCH_ID) REFERENCES TAXI_CATCH (CATCH_ID)
);











